name: Twister Github Actions Test

on:
#   push:
#     branches: [ main ]
#   pull_request:
#   schedule:
#     - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  hello_world_on_hardware:
    runs-on: [self-hosted, has-max32666fthr2]

    env:
      ZEPHYR_SDK_INSTALL_DIR: ~/zephyr-sdk-0.16.3
      
    steps:
      - uses: actions/checkout@v3

      - name: Run Twister on GPIO sample
        run: |
          cd ~/zephyrproject/zephyr
          source zephyr-env.sh
          ./scripts/twister --device-testing --hardware-map hwmap.yml -T tests/drivers/gpio/gpio_api_1pin -vvv

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: twister-artifacts
          path: |
            cd /home/ses/zephyrproject/zephyr
            twister-out/**/*.log
